name: ci

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get current date
      run: echo "date=$(date +%F)" >> $GITHUB_ENV
    - name: Get Magisk alpha
      run: |
        mkdir download
        curl https://raw.githubusercontent.com/vvb2060/magisk_files/alpha/app-release.apk -o download/app-debug.apk
    - name: Install dependencies
      run : sudo apt install setools lzip wine patchelf e2fsprogs aria2 python3 attr
    - name: Build
      run: |
        cd scripts
        sudo ./build.sh --remove-amazon --compress-format 7z --magisk-custom
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.date }}
        file: output/*.7z
